[package]
name = "bot-bus"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { package = "bot-common", path = "../bot-common" }
anyhow = "1.0.70"
serde = { version = "1.0.159", features = ["derive"] }
tokio = { version = "1.27.0", features = ["sync"] }
