[package]
name = "builder"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
chrono = "0.4.24"
regex = { version = "1.7.3", default-features = false, features = ["std", "unicode-perl"] }
walkdir = "2.3.3"
zip = "0.6.4"
