[package]
name = "builder"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.9"
chrono = "0.4.24"
regex = { version = "1.5.5", default-features = false, features = ["std", "unicode-perl"] }
walkdir = "2"
zip = "0.5.3"
