[package]
name = "oxidize"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.65"
description = "A high performance Twitch Bot powered by Rust."
documentation = "https://docs.rs/oxidize"
readme = "README.md"
homepage = "https://github.com/udoprog/OxidizeBot"
repository = "https://github.com/udoprog/OxidizeBot"
license = "MIT/Apache-2.0"
keywords = ["twitch"]
categories = ["games"]

[dependencies]
argwerk = "0.20.2"
eudex = "0.1.1"
chrono = { version = "0.4.24", features = ["serde"] }
chrono-tz = { version = "0.8.1", features = ["serde"] }
mysql_async = "0.31.3"
diesel = { version = "2.0.3", features = ["sqlite", "chrono"] }
libsqlite3-sys = { version = "0.25.2", features = ["bundled", "unlock_notify"] }
diesel_migrations = "2.0.0"
log = "0.4.17"
relative-path = { version = "1.8.0", features = ["serde"] }
serde = { version = "1.0.156", features = ["rc"] }
serde_yaml = "0.9.19"
serde_json = "1.0.94"
serde_cbor = "0.11.2"
serde_urlencoded = "0.7.1"
reqwest = "0.11.14"
Inflector = "0.11.4"
warp = "0.3.3"
tokio = { version = "1.26.0", features = ["full"] }
tokio-tungstenite = { version = "0.18.0", features = ["rustls"] }
tungstenite = "0.18.0"
tokio-stream = "0.1.12"
url = { version = "2.3.1", features = ["serde"] }
rand = "0.8.5"
fixed-map = "0.8.1"
log4rs = "1.2.0"
handlebars = "4.3.6"
lazy_static = "1.4.0"
webbrowser = "0.8.7"
parking_lot = "0.12.1"
percent-encoding = "2.2.0"
bytes = "1.4.0"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
smallvec = { version = "1.10.0", features = ["serde"] }
dirs = "4.0.0"
backoff = "0.4.0"
rust-embed = { version = "6.6.0", features = ["interpolate-folder-path"] }
mime = "0.3.16"
mime_guess = "2.0.4"
uom = "0.34.0"
crossbeam = "0.8.2"
hex = "0.4.3"
graphql_client = { version = "0.12.0", default-features = false, features = ["graphql_query_derive"] }
async-fuse = { version = "0.11.3", features = ["stream"] }
futures-cache = "0.10.1"
anyhow = "1.0.69"
thiserror = "1.0.39"
async-injector = "0.18.3"
async-trait = "0.1.66"
async-stream = "0.3.4"
leaky-bucket = "0.12.2"
regex = "1.7.1"
backtrace = "0.3.67"
futures-util = "0.3.27"
futures-core = "0.3.27"
tracing = "0.1.37"
tracing-core = "0.1.30"
tracing-futures = { version = "0.2.5", default-features = false, features = ["std-future"] }
slab = "0.4.8"
irc = "0.15.0"
ignore = "0.4.20"
notify = "5.1.0"

rune = { version = "0.12.1", optional = true }
rune-modules = { version = "0.12.1", features = ["full"], optional = true }

[build-dependencies]
winres = "0.1.12"
anyhow = "1.0.69"

[target.'cfg(target_os = "windows")'.dependencies]
futures-executor = "0.3.27"
winapi = { version = "0.3.9", features = ["shellapi", "impl-default"] }

[features]
default = []
windows = []
scripting = ["rune", "rune-modules"]
