name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - uses: udoprog/github-release@tag
      id: release
    - run: cargo run -p builder -- --version ${{steps.release.outputs.tag}}
    - uses: actions/upload-artifact@v1
      with:
        name: dist-${{matrix.os}}
        path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: udoprog/github-release@tag
      id: release
    - uses: actions/download-artifact@v1
      with: {name: dist-macos-latest, path: dist}
    - uses: actions/download-artifact@v1
      with: {name: dist-windows-latest, path: dist}
    - uses: actions/download-artifact@v1
      with: {name: dist-ubuntu-latest, path: dist}
    - uses: udoprog/github-release@v1
      with:
        files: "dist/*"
        name: ${{steps.release.outputs.tag}}
        token: ${{secrets.GITHUB_TOKEN}}
        prerelease: ${{steps.release.outputs.prerelease}}
